export const UsersData = [
    {
        id: 1,
        Name: 'John Doe',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 2,
        Name: 'Jane Smith',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 3,
        Name: 'Alice Johnson',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 4,
        Name: 'Bob Brown',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 5,
        Name: 'Charlie Davis',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 6,
        Name: 'David Wilson',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 7,
        Name: 'Emma Garcia',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 8,
        Name: 'Sophia Martinez',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 9,
        Name: 'Liam Anderson',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },
    {
        id: 10,
        Name: 'Olivia Taylor',
        Profile:'https://plus.unsplash.com/premium_photo-1675674458649-0c667500f3cc?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        Category: 'Special User',
        Bio: 'I am a strong person trying to do my best to recover myself from illness.',
        CaregiverRemarks: 'You are working great. Just focus on your medicines and diet.',
        RasberryPi_Id: 'Raspberry Pi 4',
    },



]